"""Add user model

Revision ID: 54ec4c3d83ca
Revises: 
Create Date: 2024-02-11 16:40:35.404097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '54ec4c3d83ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('registration_date', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
                    sa.UniqueConstraint('email', name=op.f('uq__user__email')),
                    sa.UniqueConstraint('id', name=op.f('uq__user__id'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
